const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(process.argv[2],'utf8');
let script=html.slice(html.indexOf('const EMBEDDED_DATA='),html.lastIndexOf('</script>'));
script=script.replace(/route\(\);loadFromServer\(false\);setInterval\(\(\)=>loadFromServer\(false\),5\*60\*1000\);\s*$/,'');
const plots=[];
const sandbox={Intl,Date,Number,Math,console,setInterval:()=>{},location:{hash:'#dashboard'},window:{addEventListener:()=>{}},document:{getElementById:()=>({})},Plotly:{newPlot:(...args)=>plots.push(args)}};
vm.createContext(sandbox);vm.runInContext(script,sandbox);
const run=x=>vm.runInContext(x,sandbox);
assert.strictEqual(run("periodDateFmt('exports','2026-07-31')"),'07.2026');
assert.strictEqual(run("periodDateFmt('production_index','2026-08-31','ytd_yoy')"),'январь–август 2026 г.');
assert.strictEqual(run("dateAxis(['2024-12-31','2025-01-31'],{monthly:true}).tickvals[1]"),'2025-01-31');
assert.ok(run("dateAxis(['2024-12-31','2025-01-31'],{monthly:true}).ticktext[1]").toLowerCase().includes('янв'));
run("state.productionMode='ytd_yoy';state.range='all';data.series.production_index.modes.ytd_yoy={dates:['2026-01-31','2026-08-31'],series:{total:[100,101],mining:[98,99],manufacturing:[102,103]}};drawProductionChart()");
let [node,traces,layout]=plots.pop();
assert.strictEqual(node,'chart');assert.strictEqual(traces[0].customdata[1],'январь–август 2026 г.');
assert.strictEqual(layout.xaxis.tickvals.at(-1),'2026-08-31');
assert.ok(layout.xaxis.ticktext.at(-1).includes('авг'));
run("state.range='all';state.tradeFrequency='monthly';drawTradeChart()");
[node,traces,layout]=plots.pop();
assert.strictEqual(layout.xaxis.tickvals.at(-1),traces[0].x.at(-1));
assert.strictEqual(traces[0].customdata.at(-1),run(`monthFmt('${traces[0].x.at(-1)}')`));
assert.ok(/[а-яё]/i.test(layout.xaxis.ticktext.at(-1)));
run("state.frequency.wci='raw';drawLineChart([{key:'wci_composite',color:'#000'}],'WCI','wci')");
[node,traces,layout]=plots.pop();
assert.strictEqual(layout.xaxis.tickvals.at(-1),traces[0].x.at(-1));
assert.ok(!/Sep|Jan/.test(layout.xaxis.ticktext.join(' ')));
run("state.frequency.rubusd='monthly';drawCurrencyChart()");
[node,traces,layout]=plots.pop();
assert.strictEqual(layout.xaxis.tickvals.at(-1),traces[0].x.at(-1));
assert.ok(traces[0].customdata.at(-1).match(/^\d{2}\.\d{4}$/));
run("state.frequency.road_freight='monthly';drawRoadChart()");
[node,traces,layout]=plots.pop();
assert.strictEqual(layout.xaxis.tickvals.at(-1),traces[0].x.at(-1));
assert.ok(traces[0].customdata.at(-1).match(/^\d{2}\.\d{4}$/));
run("state.frequency.hormuz='monthly';state.hormuzCats=Object.keys(data.series.hormuz.categories);drawHormuz()");
[node,traces,layout]=plots.pop();
assert.strictEqual(layout.xaxis.tickvals.at(-1),traces[0].x.at(-1));
assert.ok(traces[0].customdata.at(-1).match(/^\d{2}\.\d{4}$/));
console.log('Date UI: Russian labels, exact tick dates, monthly and YTD hover labels OK');
